name: Terraform Drift Detection - Prod

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3 AM UTC
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ENV: 'prod'  # Change to dev/test/prod accordingly

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="backend/backend-${ENV}.tfbackend"

      - name: Terraform Plan (Detect Drift)
        id: tf_plan
        run: |
          terraform plan -detailed-exitcode -var-file="environments/${ENV}.tfvars"
        continue-on-error: true

      - name: Evaluate Drift Status
        run: |
          if [[ "${{ steps.tf_plan.outputs.exitcode }}" == "2" ]]; then
            echo "🔍 Drift detected in ${ENV} environment!"
            exit 1
          else
            echo "✅ No drift detected."
          fi
