name: terraform-apply-Azure-Resources

on:
  push:
    branches:
      - develop
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to apply'
        required: false
        default: ''

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set Environment from Branch or Input
        id: setenv
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.environment }}" ]]; then
            echo "env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
            if [[ "$BRANCH" == "main" ]]; then
              echo "env=prod" >> $GITHUB_OUTPUT
            elif [[ "$BRANCH" == "develop" ]]; then
              echo "env=dev" >> $GITHUB_OUTPUT
            else
              echo "env=test" >> $GITHUB_OUTPUT
            fi
          fi
      - name: Debug - Print Environment
        run: echo "ENV = ${{ steps.setenv.outputs.env }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Copy correct tfvars file
        run: |
          cp environments/${{ steps.setenv.outputs.env }}.tfvars selected.tfvars

      - name: Replace Tokens in tfvars
        uses: cschleiden/replace-tokens@v1
        with:
          files: selected.tfvars
        env:
          admin_username: ${{ secrets.ADMIN_USERNAME }}
          admin_password: ${{ secrets.ADMIN_PASSWORD }}
          app_location: ${{ secrets.APP_LOCATION }}
          db_location: ${{ secrets.DB_LOCATION }}
          msg_location: ${{ secrets.MSG_LOCATION }}
          sm_location: ${{ secrets.SM_LOCATION }}
          aks_location: ${{ secrets.AKS_LOCATION }}
          location: ${{ secrets.LOCATION }}
          resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
          vm_name: ${{ secrets.VM_NAME }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          environment: ${{ secrets.ENVIRONMENT }}
          sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
          sql_admin_username: ${{ secrets.SQL_ADMIN_USERNAME }}
          subnet_cidr_blocks: ${{ secrets.SUBNET_CIDR_BLOCKS }}
          subnet_name: ${{ secrets.SUBNET_NAME }}
          subnet_names: ${{ secrets.SUBNET_NAMES }}
          tenant_id: ${{ secrets.TENANT_ID }}
          vm_size: ${{ secrets.VM_SIZE }}
          address_space: ${{ secrets.ADDRESS_SPACE }}

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="backend/backend-${{ steps.setenv.outputs.env }}.tfbackend"

      - name: Terraform Plan
        run: terraform plan -var-file="selected.tfvars.tfvars"

      - name: Terraform Apply
        run: terraform apply -var-file="selected.tfvars" -auto-approve
